# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:

  nginx:
    container_name: docker_nginx
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - 80:80
#      - 443:443
    depends_on:
      - php
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ../www:/var/www
      - ./logs:/var/log/nginx
    networks:
      - ng-link


  php:
    container_name: docker_php
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    volumes:
      - ../www:/var/www
    networks:
      - ng-link


  # MySQL сервер
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ng-link


  # PhpMyAdmin service for Percona DBMS management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    ports:
      - 8090:80
    networks:
      - ng-link

# Создание сети
networks:
  ng-link:
    driver: bridge
